// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccazghkiaiowdshwupjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjYXpnaGtpYWlvd2RzaHd1cGp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MTM1OTksImV4cCI6MjA3MTA4OTU5OX0.8u6uub1srr6oABPYjy6qgWe2fOSqQkwtzK4UDWpCMQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});